/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#include "stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(uint32_t time) {
    for (uint32_t i = 0; i < time * 4000; i++) {
        __NOP(); // No Operation, samo da uspori
    }
}

void GPIO_Init(void) {
    // 1. Uključi clock za GPIOD
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;

    // 2. Postavi PD12 kao izlaz
    GPIOD->MODER |= (1 << (12 * 2));  // Output mode
    GPIOD->OTYPER &= ~(1 << 12);      // Push-pull
    GPIOD->OSPEEDR |= (3 << (12 * 2)); // High speed
    GPIOD->PUPDR &= ~(3 << (12 * 2));  // No pull-up/down
}

int main(void)
{
    GPIO_Init();

    while (1) {
        GPIOD->ODR ^= (1 << 12); // Toggle PD12
        delay(500); // Oko 500ms
    }
}
